#!/usr/bin/env sh

SRC="apps/wiki/docs/"
DEST="/mnt/d/kxh/10-wiki/"

echo "[post-commit] Syncing $SRC -> $DEST"

rsync -a --delete "$SRC" "$DEST"
rc=$?

if [ $rc -ne 0 ]; then
  echo "[post-commit] Sync failed (code $rc), push aborted."
  exit $rc
fi

echo "[post-commit] Sync completed."
exit 0
