#!/usr/bin/env sh

SRC="apps/wiki/docs/"
DEST="/mnt/d/kxh/10-wiki/"

if git diff-tree --no-commit-id --name-only -r HEAD | grep -q "^$SRC"; then
  echo "[post-commit] Syncing $SRC -> $DEST"

  rm -rf "${DEST:?}"*
  cp -rf "${SRC:?}"* "$DEST"
  rc=$?

  if [ $rc -ne 0 ]; then
    echo "[post-commit] Sync failed (code $rc)."
    exit $rc
  fi

  echo "[post-commit] Sync completed."
else
  echo "[post-commit] No changes in $SRC, skipped."
fi
exit 0
