import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  root: [{ type: "autogenerated", dirName: "." }],
  sop: [{ type: "autogenerated", dirName: "20-SOP" }],
  live: [{ type: "autogenerated", dirName: "30-生活" }],
  learn: [{ type: "autogenerated", dirName: "40-学习" }],
  ai: [{ type: "autogenerated", dirName: "50-AI" }],
  computer: [{ type: "autogenerated", dirName: "60-计算机" }],
  tool: [{ type: "autogenerated", dirName: "80-工具" }],
  backup: [{ type: "autogenerated", dirName: "90-存档" }],
};

export default sidebars;
