import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  root: [{ type: "autogenerated", dirName: "." }],
  sop: [{ type: "autogenerated", dirName: "020-SOP" }],
  live: [{ type: "autogenerated", dirName: "030-生活" }],
  learn: [{ type: "autogenerated", dirName: "040-学习" }],
  ai: [{ type: "autogenerated", dirName: "050-AI" }],
  computer: [{ type: "autogenerated", dirName: "060-计算机" }],
  tool: [{ type: "autogenerated", dirName: "080-工具" }],
};

export default sidebars;
